NedTrainHourRegistration/Controllers/HourRegistrationController.cs
namespace NedTrainHourRegistration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Globalization;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.Security;
    using NedTrainHourRegistration.Models;
    using NedTrainHourRegistration.NedTrainServiceReference;
    using NedTrainHourRegistration.ViewModels;
    using NedTrainHourRegistration.Infrastructure;
    using HourRegistration.BusinessLogic.Int;
    using HourRegistration.BusinessLogic.Impl;
    using HourRegistration.DataAccess.Xml;
    using PublicEntities = HourRegistration.PublicEntities;
    using System.Web.Script.Serialization;
    using System.Diagnostics;
    using System.Net.Mail;
    using DnsClient;

    public class HourRegistrationController : Controller
    {
        private readonly ERPService_NedTrainSoapClient serviceClient;
        private string employeeId;
        private HoursPerWeekModel currentModel;
        private WeeklyHoursPerEmployeePE recentHours;

        public HourRegistrationController()
        {
            this.serviceClient = new ERPService_NedTrainSoapClient();

            if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
            {
                this.employeeId = System.Web.HttpContext.Current.User.Identity.Name.Split('|')[2];
            }
            TempData["sendMessage"] = "";
        }

        [Authorize]
        [HttpPost]
        public JsonResult WeekDayChanged(string currentWeek, string weekday)
        {
            ErpOutputOfDailyTimeSlotPE timeSlot = null;
            HoursPerWeekModel model = (HoursPerWeekModel)HttpContext.Session["HourModel"];
            DateTime firstDateOfWeek = DateTime.ParseExact(currentWeek.Substring(0, 10), "dd-MM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None);
            DateTime selectedDate = firstDateOfWeek.AddDays(this.GetDayNumber(weekday));

            int userId = (int)HttpContext.Session["UserCode"];
            timeSlot = this.serviceClient.RetrieveDailyTimeSlot(this.employeeId, userId, selectedDate);

            DateTime startTime = new DateTime(selectedDate.Year, selectedDate.Month, selectedDate.Day, 0, 0, 0);
            DateTime stopTime = new DateTime(selectedDate.Year, selectedDate.Month, selectedDate.Day, 23, 59, 59);

            if (timeSlot.Entities != null && timeSlot.Entities.Length > 0)
            {
                startTime = timeSlot.Entities[0].StartTime;
                stopTime = timeSlot.Entities[0].StopTime;
            }

            if (model.LoggedHours != null)
            {
                var recentHours = (from hours in model.LoggedHours
                                   where hours.StartTime.Date == selectedDate.Date
                                   orderby hours.StartTime descending, hours.SequenceNr descending
                                   select hours).FirstOrDefault();

                if (recentHours != null)
                {
                    startTime = recentHours.EndTime;
                }
            }

            var timeslotResult = new { StartTime = string.Format("{0:HH:mm}", startTime), StopTime = string.Format("{0:HH:mm}", stopTime) };
            return this.Json(timeslotResult, "application/json");
        }

        [Route("")]
        public ActionResult Login()
        {
            ViewBag.CompNr = ConfigurationManager.AppSettings["CompNr"] as string;
            if (User.Identity.IsAuthenticated)
            {
                int weekNumber = this.GetIso8601WeekOfYear(DateTime.Now);
                return this.RedirectToAction("Index", new { year = DateTime.Now.Year, weekNumber = weekNumber });
            }
            ViewBag.globalMessage = TempData["sendMessage"];
            ViewBag.results = TempData["returnResult"];
            return this.View();
        }

        [HttpPost]
        [Route("")]
        public ActionResult Login(LoginModel model, string message = "")
        {           
            if (!ModelState.IsValid)
            {
                if (model.CompNr == 0)
                {
                    ViewBag.CompNr = ConfigurationManager.AppSettings["CompNr"] as string;
                }

                return this.View(model);
            }

            ViewBag.results = TempData["returnResult"];
            TempData["wasSuccess"] = "FALSE";
            try
            {
                var result = this.serviceClient.Login(model.LoginCode, model.Password, model.CompNr);

                if (!result.IsAuthenticated)
                {
                    throw new Exception("De opgegeven combinatie van inlogcode en wachtwoord is onjuist");
                }

                if (Session["UserDefaults"] == null)
                {

                    var UserDefaults = new UserDefaults();

                    // Ophalen van defaults van de ingelogde gebruiker
                    var userDefaults = this.serviceClient.RetrieveUserDefaults(model.CompNr + model.LoginCode);

                    var UserDefaultsFromBaan = new JavaScriptSerializer().Serialize(userDefaults);
                    Session.Add("UserDefaultsFromBaan", UserDefaultsFromBaan);

                    string ZoekMethod = userDefaults.Entities[0].Method.ToString();
                    methods method = (methods)Enum.Parse(typeof(methods), ZoekMethod);
                    UserDefaults.method = method;

                    string ZoekInputMethod = userDefaults.Entities[0].InputMethod.ToString();
                    inputMethods InputMethod = (inputMethods)Enum.Parse(typeof(inputMethods), ZoekInputMethod);
                    UserDefaults.inputMethod = InputMethod;

                    string ZoekZoomMethod = userDefaults.Entities[0].ZoomMethod.ToString();
                    zoomMethods zoomMethod = (zoomMethods)Enum.Parse(typeof(zoomMethods), ZoekZoomMethod);
                    UserDefaults.zoomMethod = zoomMethod;

                    UserDefaults.employeeId = model.CompNr + model.LoginCode;
                    Session.Add("UserDefaults", UserDefaults);
                }

                FormsAuthentication.SetAuthCookie($"{result.EmployeeCode}|{result.Name}|{model.CompNr}{model.LoginCode}", false);

                HttpContext.Session["UserLoginCode"] = model.LoginCode;
                HttpContext.Session["UserPassword"] = model.Password;
                HttpContext.Session["UserCode"] = result.EmployeeCode;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "De gebruiker kon niet worden gevonden. Controleer de login code en probeer het opnieuw.");
                ViewBag.CompNr = ConfigurationManager.AppSettings["CompNr"] as string;
                return this.View(model);
            }
            int weekNumber = this.GetIso8601WeekOfYear(DateTime.Now);
            return this.RedirectToAction("Index", new { year = DateTime.Now.Year, weekNumber = weekNumber });
        }

        public ActionResult ResetPassword()
        {
            ResetPasswordModel model = new ResetPasswordModel();
            ViewBag.CompNr = ConfigurationManager.AppSettings["CompNr"] as string;

            return this.View(model);
        }

        [HttpPost]
        public ActionResult ResetPassword(ResetPasswordModel model)
        {
            SmtpClient client = new System.Net.Mail.SmtpClient();

            string to = "nedtrain-it-sd-team-reno-haarlem@ns.nl";

            string from = "webhra@ns.nl";

            string server = "mailrelay.ns.nl";

            string poort = "25";

            bool ssl = false;

            MailMessage message = new MailMessage(from, to);

            message.Subject = "Aanvraag nieuw wachtwoord WebHRA";

            message.Body = @"Er is een aanvraag binnen gekomen voor een nieuw wachtwoord voor gebruiker " + model.LoginCode + ". <br> U kunt het nieuwe wachtwoord opsturen naar <a href='mailto:" + model.emailAddress + "'>" + model.emailAddress + "</a>";

            message.Bcc.Add("jeroen.verhoeven@ns.nl");

            message.IsBodyHtml = true;

            client = new System.Net.Mail.SmtpClient
            {
                Host = server,
                Port = Convert.ToInt32(poort),
                EnableSsl = Convert.ToBoolean(ssl),
                DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
            };

            try
            {
                TempData["sendMessage"] = "Uw aanvraag voor een nieuw wachtwoord is verstuurd";
                client.Send(message);
            }
            catch (Exception ex)
            {
                TempData["sendMessage"] = "Exception caught in CreateTestMessage2(): {0}" + ex.ToString();
            }

            return this.RedirectToAction("Login");
        }

        [Authorize]
        [Route("uitloggen")]
        public ActionResult LogOut()
        {
            HttpContext.Session["year"] = null;
            HttpContext.Session["week"] = null;
            HttpContext.Session["HourModel"] = null;
            HttpContext.Session["UserCode"] = null;
            FormsAuthentication.SignOut();

            Session.Clear();

            return this.RedirectToAction("Login");
        }

        [Authorize]
        [Route("uren/{year}/{weekNumber}")]
        [SessionAvailable]
        public ActionResult Index(int year, int weekNumber, string weekDay = "", string results = "")
        {

            HoursPerWeekModel model = new HoursPerWeekModel();
            ErpOutputOfDailyTimeSlotPE timeSlot = null;

            var holdYear = HttpContext.Session["year"];
            var holdWeek = HttpContext.Session["week"];

            int indirectHours = 0;
            int directHours = 0;

            int userId = 0;

            try
            {
                userId = (int)HttpContext.Session["UserCode"];
            }
            catch (Exception e){

NedTrainHourRegistration/Controllers/SearchMasterDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using HourRegistration.BusinessLogic.Impl;
using HourRegistration.BusinessLogic.Int;
using HourRegistration.DataAccess.Xml;
using HourRegistration.PublicEntities;
using NedTrainHourRegistration.ViewModels;

namespace NedTrainHourRegistration.Controllers
{  
    public class SearchMasterDataController : Controller
    {
        private IProjectRepository projectRepos;
        private IProjectActivityRepository activityRepos;
        private IIndirectTaskRepository taskRepos;
        
        public SearchMasterDataController()
        {
            this.projectRepos = new ProjectRepository(new ProjectDataAccessor(new XmlAppSettings()));
            this.activityRepos = new ProjectActivityRepository(new ProjectActivityDataAccessor(new XmlAppSettings()));
            this.taskRepos = new IndirectTaskRepository(new IndirectTaskDataAccessor(new XmlAppSettings()));
        }

        [Authorize]
        [HttpPost]
        public ActionResult GetActivitiesByProject(string projectCode)
        {
            List<ProjectActivityPE> activities = this.activityRepos.RetrieveActivitiesByProject(projectCode);
            return this.Json(activities, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public PartialViewResult SearchMasterDataPartialView(string hourType)
        {
            SearchMasterDataModel searchMasterData = new SearchMasterDataModel();
            int typeIndex = int.Parse(hourType);
            searchMasterData.HourType = int.Parse(hourType);
            return PartialView("_SearchMasterData", searchMasterData);
        }

        [Authorize]
        public PartialViewResult SearchActivitiesByProjectPartialView(SearchMasterDataModel model)
        {
            if (!string.IsNullOrEmpty(model.ProjectCode))
            {
                model.ActivitiesByProject = this.activityRepos.RetrieveActivitiesByProject(model.ProjectCode);
            }

            return PartialView("_SearchMasterData", model);
        }

        [HttpPost]
        public JsonResult SelectProjectInfo(SearchMasterDataModel model)
        {
            model.ActivitiesByProject = null;
            if (!string.IsNullOrEmpty(model.ProjectCode))
            {
                model.ActivitiesByProject = this.activityRepos.RetrieveActivitiesByProject(model.ProjectCode);
            }

            return Json(model);
        }

        [Authorize]
        public PartialViewResult ListProjectData()
        {
            List<ProjectPE> projects = this.projectRepos.RetrieveProjects();

            SearchProjectModel searchProjects = new SearchProjectModel()
            {
                Projects = projects,
                FilteredProjects = projects,
                SearchKey = string.Empty
            };

            return PartialView("_ListProjectData", searchProjects);
        }

        [Authorize]
        public PartialViewResult FilterProjects(SearchProjectModel model)
        {
            List<ProjectPE> projects = this.projectRepos.RetrieveProjects();
            model.Projects = projects;
            model.FilteredProjects = projects;

            if (!string.IsNullOrEmpty(model.SearchKey))
            {
                model.FilteredProjects = (from project in projects
                                          where project.SearchString.IndexOf(model.SearchKey, StringComparison.OrdinalIgnoreCase) >= 0
                                          select project).ToList();
            }

            return PartialView("_ListProjectData", model);
        }

        [Authorize]
        public PartialViewResult ListTaskData()
        {
            List<IndirectTaskPE> indirectTasks = this.taskRepos.RetrieveIndirectTasks();

            SearchIndirectTaskModel searchTasks = new SearchIndirectTaskModel()
            {
                IndirectTasks = indirectTasks,
                FilteredTasks = indirectTasks,
                SearchKey = string.Empty
            };

            return PartialView("_ListIndirectTasks", searchTasks);
        }

        [Authorize]
        public PartialViewResult FilterIndirectTasks(SearchIndirectTaskModel model)
        {
            List<IndirectTaskPE> indirectTasks = this.taskRepos.RetrieveIndirectTasks();
            model.IndirectTasks = indirectTasks;
            model.FilteredTasks = indirectTasks;

            if (!string.IsNullOrEmpty(model.SearchKey))
            {
                model.FilteredTasks = (from singleTask in indirectTasks
                                 where singleTask.SearchString.IndexOf(model.SearchKey, StringComparison.OrdinalIgnoreCase) >= 0
                                 select singleTask).ToList();
            }

            return PartialView("_ListIndirectTasks", model);
        }
    }
}

NedTrainHourRegistration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WebHRA - v @typeof(NedTrainHourRegistration.MvcApplication).Assembly.GetName().Version.ToString(3)</title>
    @using System.Web.Optimization
    @Styles.Render("~/bundles/master/css")
    @Scripts.Render("~/bundles/master/init/js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand-erpplus" href="/">
                    <img src="~/Content/images/logoned.png" />
                    <span class="logo-title">WebHRA</span>
                </a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a href="@Url.Action("Login", "HourRegistration")"><i class="fa fa-clock-o size-nav-icon"></i>Registreer uren</a></li>
                        <li><a href="@Url.Action("Index", "UserDefaults")"><i class="fa fa-user size-nav-icon"></i>Standaard instellingen</a></li>
                        <li><a href="@Url.Action("LogOut", "HourRegistration")"><i class="fa fa-sign-out size-nav-icon"></i>Uitloggen</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer class="erpplus-footer">
        <div class="container">
            <hr class="erpplus-footer-hr" />
            <p>&copy; @DateTime.Now.Year - WebHRA - Treshold Automatisering - Versie: @typeof(NedTrainHourRegistration.MvcApplication).Assembly.GetName().Version.ToString(3)</p>
        </div>
    </footer>
    @RenderSection("scripts", required: false)

    <script>
            var SearchMasterDataPartialViewvarHourType = "@Url.Action("SearchMasterDataPartialView", "SearchMasterData", new { hourType = "varHourType" })";
            var SearchMasterDataPartialView1 = "@Url.Action("SearchMasterDataPartialView", "SearchMasterData", new { hourType = 1 })";
            var SearchMasterDataPartialView4 = "@Url.Action("SearchMasterDataPartialView", "SearchMasterData", new { hourType = 4 })";
            var SelectProjectInfo = "@Url.Action("SelectProjectInfo", "SearchMasterData")";
            var GetActivitiesByProject = "@Url.Action("GetActivitiesByProject", "SearchMasterData")";
            var WeekDayChanged = "@Url.Action("WeekDayChanged", "HourRegistration")";
            var LayoutDateTime = "@ViewBag.DateTime";
            var Filter = "@Url.Action("FilterProjects", "SearchMasterData", new { SearchKey = "varSearchKey" })";
    </script>

    <script src="~/Scripts/moment-with-locales.js"></script>

    @Scripts.Render("~/bundles/master/custom/js")

</body>
</html>

NedTrainHourRegistration/Views/Shared/_ListIndirectTasks.cshtml
@model SearchIndirectTaskModel

<form id="selectIndirectTask">
    <table class="table">
        <tr>
            <td>Zoek:</td>
            <td>
                @Html.EditorFor(model => model.SearchKey, new { style = "width:100px" })
                <button type="button" id="btnFilterTasks" class="btn">Filter</button>
            </td>
            <td></td>
        </tr>
        <tr>
            <th>
                @if (Model.FilteredTasks != null && Model.FilteredTasks.Count > 0)
                {
                    @Html.DisplayNameFor(model => model.FilteredTasks[0].Task)
                }
            </th>
            <th>
                @if (Model.FilteredTasks != null && Model.FilteredTasks.Count > 0)
                {
                    @Html.DisplayNameFor(model => model.FilteredTasks[0].Description)
                }
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.FilteredTasks)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Task)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @{int taskId = item.Task;
                        <button type="button" class="btn" onclick="TaskSelected(@taskId)">Select</button>
                    }
                </td>
            </tr>
        }
    </table>
</form>

<script type="text/javascript">
    $(document).ready(function () {

        $('#btnFilterTasks').on('click', function () {
            filter();
        })

    });

    function TaskSelected(taskId) {
        var $parentForm = $(this).closest('form').closest('form');
        var textbox = document.getElementById('IndirectTask');
        textbox.value = taskId;
        $('#masterData').empty();
        $('#IndirectTask').change();
    }

</script>

NedTrainHourRegistration/Views/Shared/_ListProjectData.cshtml
@model SearchProjectModel

<form id="selectProject">
    <table class="table">
        <tr>
            <td>Zoek:</td>
            <td>
                @Html.EditorFor(model => model.SearchKey, new { style = "width:100px" })
                <button type="button" id="btnFilterProject" class="btn">Filter</button>
            </td>
            <td></td>
        </tr>
        <tr>
            <th>
                @if (Model.FilteredProjects != null && Model.FilteredProjects.Count > 0)
                {
                    @Html.DisplayNameFor(model => model.FilteredProjects[0].Code)
                }
            </th>
            <th>
                @if (Model.FilteredProjects != null && Model.FilteredProjects.Count > 0)
                {
                    @Html.DisplayNameFor(model => model.FilteredProjects[0].Description)
                }
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.FilteredProjects)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @{string projectCode = item.Code;
                        <button type="button" class="btn" onclick="ProjectSelected(@projectCode)">Select</button>
                    }
                </td>
            </tr>
        }
    </table>
</form>

<script type="text/javascript">
    $(document).ready(function () {

        $('#btnFilterProject').on('click', function () {
            filter();
        })

    });

    function ProjectSelected(projectCode) {
        var $parentForm = $(this).closest('form').closest('form');
        var textbox = document.getElementById('ProjectCode');
        textbox.value = projectCode;
        $('#masterData').empty();
        $('#ProjectCode').change();
    }

</script>

NedTrainHourRegistration/Views/Shared/_SearchMasterData.cshtml
@model SearchMasterDataModel

<form id="searchForm">
    <div class="row">
        <div class="modal-row-1"></div>
    </div>
    <div class="row">
        <div class="col-sm-5">
            <div id="divHourType" class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-3 modal-col-1">
                    @Html.LabelFor(m => m.HourType)
                </div>
                <div class="col-sm-6 modal-col-1">
                    @Html.DropDownListFor(m => m.HourType, new SelectList(Model.HourTypes(), "Key", "Value", Model.HourType), new { htmlAttributes = new { @id = "searchHourType" } })
                </div>
            </div>
            @if (Model.HourType == 1)
            {
                <div id="divProject" class="row">
                    <div class="col-sm-1"></div>
                    <div class="col-sm-3 modal-col-1">
                        @Html.LabelFor(m => m.ProjectCode)
                    </div>
                    <div class="col-sm-4 modal-col-1">
                        @Html.EditorFor(m => m.ProjectCode)
                    </div>
                    <div class="col-sm-2">
                        <button type="button" id="btnListProjectData" class="btn">...</button>
                    </div>
                </div>
                <div id="divActivity" class="row">
                    <div class="col-sm-1"></div>
                    <div class="col-sm-3 modal-col-1">
                        @Html.LabelFor(m => m.ActivityCode)
                    </div>
                    <div class="col-sm-4 modal-col-1">
                        @if (Model.ActivitiesByProject != null)
                        {
                            @Html.DropDownListFor(m => m.ActivityCode, new SelectList(Model.ActivitiesByProject, "ActivityCode", "ListItem"))
                        }
                    </div>
                </div>
            }
            @if (Model.HourType == 4)
            {
            <div id="divTask" class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-3 modal-col-1">
                    @Html.LabelFor(m => m.IndirectTask)
                </div>
                <div class="col-sm-4 modal-col-1">
                    @Html.EditorFor(m => m.IndirectTask)
                </div>
                <div class="col-sm-2">
                    <button type="button" id="btnListTaskData" class="btn">...</button>
                </div>
            </div>
            }
        </div>
        <div id="masterData" class="col-sm-7">
        </div>
    </div>
</form>

<script type="text/javascript">
    $(document).ready(function () {
        $('#HourType').change(function () {
            var parms = '?HourType=' + $('#HourType').val();
            var link = '@Url.Action("SearchMasterDataPartialView", "SearchMasterData")' + parms;
            $('#divSearchData').load(link);
        });

        $('#btnListProjectData').on('click', function () {
            var link = '@Url.Action("ListProjectData", "SearchMasterData")';
            $('#masterData').load(link);
        });

        $('#btnListTaskData').on('click', function () {
            var link = '@Url.Action("ListTaskData", "SearchMasterData")';
            $('#masterData').load(link);
        });

        $('#ProjectCode').change(function () {
            var parms = '?HourType=' + $('#HourType').val();
            parms = parms + '&ProjectCode=' + $('#ProjectCode').val();
            parms = parms + '&IndirectTask=' + $('#IndirectTask').val();
            var link = '@Url.Action("SearchActivitiesByProjectPartialView", "SearchMasterData")' + parms;
            $('#divSearchData').load(link);
        });
    });
</script>